services:
  - type: web
    name: law-firm-backend
    env: node
    buildCommand: npm install && npm run server:build
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1